#!/usr/bin/env python3
"""Generate Markdown documentation for OpenType character alternatives."""

import argparse
from pathlib import Path

import matplotlib
import pathops
from fontTools.pens.recordingPen import RecordingPen

matplotlib.use("Agg")
import matplotlib.patches as patches
import matplotlib.pyplot as plt
from matplotlib.path import Path as MatplotlibPath

from config import DrawConfig, FontConfig
from generate_font import discover_glyphs


DEFAULT_OUTPUT = Path("doc/alternative_characters.md")
IMAGE_SIZE = (96, 128)


def collect_alternatives():
    glyphs = discover_glyphs()
    defaults = {
        int(glyph.unicode, 16): glyph
        for glyph in glyphs
        if glyph.unicode and not glyph.font_feature
    }
    alternatives = []
    for glyph in glyphs:
        if not glyph.font_feature or not glyph.unicode:
            continue

        codepoint = int(glyph.unicode, 16)
        default = defaults.get(codepoint)
        if default is None:
            raise ValueError(f"No default glyph found for U+{codepoint:04X}")
        for feature, index in glyph.font_feature.items():
            alternatives.append(
                (
                    feature,
                    index,
                    chr(codepoint),
                    f"U+{codepoint:04X}",
                    default,
                    glyph,
                )
            )

    return sorted(alternatives, key=lambda item: (item[0], item[1], item[5].name))


def _matplotlib_path(recording):
    vertices = []
    codes = []
    contour_start = None
    for operation, points in recording.value:
        if operation == "moveTo":
            contour_start = points[0]
            vertices.append(contour_start)
            codes.append(MatplotlibPath.MOVETO)
        elif operation == "lineTo":
            vertices.append(points[0])
            codes.append(MatplotlibPath.LINETO)
        elif operation == "curveTo":
            vertices.extend(points)
            codes.extend([MatplotlibPath.CURVE4] * 3)
        elif operation == "closePath":
            vertices.append(contour_start)
            codes.append(MatplotlibPath.CLOSEPOLY)
    return MatplotlibPath(vertices, codes)


def render_glyph_png(glyph, output):
    outline = pathops.Path()
    glyph.draw(pathops.PathPen(outline), dc=DrawConfig())
    outline = pathops.simplify(
        outline, clockwise=False, keep_starting_points=True
    )
    recording = RecordingPen()
    outline.draw(recording)

    dpi = 128
    figure = plt.figure(
        figsize=(IMAGE_SIZE[0] / dpi, IMAGE_SIZE[1] / dpi),
        dpi=dpi,
        facecolor="none",
    )
    axis = figure.add_axes((0, 0, 1, 1))
    axis.add_patch(
        patches.PathPatch(
            _matplotlib_path(recording),
            facecolor="#222222",
            edgecolor="none",
        )
    )
    axis.set_xlim(0, FontConfig.window_width)
    axis.set_ylim(FontConfig.window_descent, FontConfig.window_ascent)
    axis.set_aspect("equal")
    axis.set_axis_off()
    figure.savefig(output, dpi=dpi, transparent=True)
    plt.close(figure)


def generate_images(alternatives, image_dir):
    image_dir.mkdir(parents=True, exist_ok=True)
    glyphs = {
        glyph.name: glyph
        for alternative in alternatives
        for glyph in alternative[4:6]
    }
    for glyph in glyphs.values():
        render_glyph_png(glyph, image_dir / f"{glyph.name}.png")


def render_markdown(alternatives, image_dir_name):
    lines = [
        "# Alternative Characters",
        "",
        "<!-- Generated by `python -m scripts.alternatives_markdown`. -->",
        "",
        "| Feature | Character | Code point | Default | Alternative | Alternative glyph |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{feature}={index}` | `{character}` | `{codepoint}` "
        f"| ![{default.name}]({image_dir_name}/{default.name}.png) "
        f"| ![{alternative.name}]({image_dir_name}/{alternative.name}.png) "
        f"| `{alternative.name}` |"
        for feature, index, character, codepoint, default, alternative in alternatives
    )
    lines.append("")
    return "\n".join(lines)


def generate(output=DEFAULT_OUTPUT):
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    alternatives = collect_alternatives()
    image_dir = output.with_suffix("")
    generate_images(alternatives, image_dir)
    output.write_text(
        render_markdown(alternatives, image_dir.name),
        encoding="utf-8",
    )
    print(f"Saved {output}")
    print(f"Saved {len({g.name for row in alternatives for g in row[4:6]})} images to {image_dir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Markdown documentation for character alternatives"
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file (default: {DEFAULT_OUTPUT})",
    )
    generate(parser.parse_args().output)
