#!/usr/bin/env python3
"""Generate Markdown documentation for OpenType character alternatives."""

import argparse
from pathlib import Path

from generate_font import discover_glyphs


DEFAULT_OUTPUT = Path("doc/alternative_characters.md")


def collect_alternatives():
    alternatives = []
    for glyph in discover_glyphs():
        if not glyph.font_feature or not glyph.unicode:
            continue

        codepoint = int(glyph.unicode, 16)
        for feature, index in glyph.font_feature.items():
            alternatives.append(
                (feature, index, chr(codepoint), f"U+{codepoint:04X}", glyph.name)
            )

    return sorted(alternatives, key=lambda item: (item[0], item[1], item[4]))


def render_markdown(alternatives):
    lines = [
        "# Alternative Characters",
        "",
        "<!-- Generated by `python -m scripts.alternatives_markdown`. -->",
        "",
        "| Feature | Character | Code point | Alternative glyph |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{feature}={index}` | `{character}` | `{codepoint}` | `{name}` |"
        for feature, index, character, codepoint, name in alternatives
    )
    lines.append("")
    return "\n".join(lines)


def generate(output=DEFAULT_OUTPUT):
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(collect_alternatives()), encoding="utf-8")
    print(f"Saved {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Markdown documentation for character alternatives"
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file (default: {DEFAULT_OUTPUT})",
    )
    generate(parser.parse_args().output)
